window:
  opacity: 0.95
  decorations: none

font:
  normal:
    family: "monospace"
    size: 11

colors:
  primary:
    background: '0x0d1117'
    foreground: '0xc9d1d9'
  cursor:
    text: '0x0d1117'
    cursor: '0x58a6ff'
